
echo "PREPS_HOME=[${PREPS_HOME}]"
echo "GIO_RELEASE_VERSION=[${GIO_RELEASE_VERSION}]"
echo "BUCKET_CONTENT_HOME=[${BUCKET_CONTENT_HOME}]"
ls -allh ${PREPS_HOME}
ls -allh ${BUCKET_CONTENT_HOME}

tsc && npm start

echo "PREPS_HOME=[${PREPS_HOME}]"
echo "GIO_RELEASE_VERSION=[${GIO_RELEASE_VERSION}]"
echo "BUCKET_CONTENT_HOME=[${BUCKET_CONTENT_HOME}]"
ls -allh ${PREPS_HOME}
ls -allh ${BUCKET_CONTENT_HOME}
tree ${BUCKET_CONTENT_HOME}

echo "Now you need to retrieve BUCKET_CONTENT_HOME=[${BUCKET_CONTENT_HOME}] on Host"
